on:
  rss:
    url:
      - http://evangelizo.org/rss/v2/evangelizo_rss-de.xml
      - https://rss.evangelizo.org/rss/v2/evangelizo_rss-de.xml
    config:
      every: "30 8,12 * * *"
      filter:
        content:
          $regex: ....+
        categories:
          $regex: EVANGELIUM
      format: |
        item.contentSnippet = 'https://www.startpage.com/do/dsearch?query=' + item.title.substring(item.title.search(' : ') + 3).replace(/ /g, '%20').replace(/,/g, '%2C').replace(/\./g, '%2E').replace(/-/g, '%2D')
        return item;
jobs:
  send2matrix:
    runs-on: ubuntu-latest
    steps:
      - name: send message
        uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ secrets.MATRIX_ROOM_ID }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          message: |
               ${{on.rss.outputs.title}}
               ${{on.rss.outputs.contentSnippet}}
               
               ${{on.rss.outputs.content}}
               
               ${{on.rss.outputs.link}}
              
          server: "synod.im"
