on:
  rss:
    url:
      - http://evangelizo.org/rss/v2/evangelizo_rss-de.xml
      - https://rss.evangelizo.org/rss/v2/evangelizo_rss-de.xml
    config:
      every: "0 7,11 * * *"
      filter:
        content:
          $regex: ....+
        categories:
          $regex: LECTIO.1
      format: |
        item.contentSnippet = 'https://www.startpage.com/do/dsearch?query=' + item.title.substring(item.title.search(' : ') + 3).replace(/ /g, '%20').replace(/,/g, '%2C').replace(/\./g, '%2E').replace(/-/g, '%2D')
        return item;
jobs:
  send2matrix:
   runs-on: ubuntu-latest
   steps:
     - name: send titel
       uses: s3krit/matrix-message-action@v0.0.3
       with:
         room_id: ${{ secrets.MATRIX_ROOM_ID }}
         access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
         message: |
              ${{on.rss.outputs.title}}
              (Quelle: ${{on.rss.outputs.link}})
              
         server: "synod.im"
     - name: send lectio
       uses: s3krit/matrix-message-action@v0.0.3
       with:
         room_id: ${{ secrets.MATRIX_ROOM_ID }}
         access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
         message: |
              ${{on.rss.outputs.content}}
              
         server: "synod.im"    
     - name: send websuche
       uses: s3krit/matrix-message-action@v0.0.3
       with:
         room_id: ${{ secrets.MATRIX_ROOM_ID }}
         access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
         message: |
              --
              
              Im Web nach der Schriftstelle suchen:
              ${{on.rss.outputs.contentSnippet}}
              
              ----------
         server: "synod.im"
