on:
  rss:
    url:
      - http://evangelizo.org/rss/v2/evangelizo_rss-de.xml
      - https://rss.evangelizo.org/rss/v2/evangelizo_rss-de.xml
    config:
      every: "30 7,11 * * *"
      filter:
        content:
          $regex: ....+
        categories:
          $regex: PSALMUS
      format: |
        item.contentSnippet = 'https://www.startpage.com/do/dsearch?query=' + item.title.substring(item.title.search(' : ') + 3).replace(/ /g, '%20').replace(/,/g, '%2C').replace(/\./g, '%2E').replace(/-/g, '%2D')
        return item;
jobs:
  send2matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Get textstelle
        id: kapitel
        run: echo "::set-output name=stelle::"$(echo "${{on.rss.outputs.title}}" | awk -F" " '{print $NF}')
      - name: Get buch
        id: buch
        run: |
          if [[ "${{on.rss.outputs.title}}" == *"ps"* ]]
          then
            echo "::set-output name=name::ps"
          elif [[ "${{on.rss.outputs.title}}" == *"Lukas"* ]]
          then
            echo "::set-output name=name::Lukas"
          elif [[ "${{on.rss.outputs.title}}" == *"Matthäus"* ]]
          then
            echo "::set-output name=name::Matthäus"
          elif [[ "${{on.rss.outputs.title}}" == *"Markus"* ]]
          then
            echo "::set-output name=name::Markus"
          else
            echo "::set-output name=name::unbekannt"
          fi 
      - name: Get link
        id: link
        run: echo "::set-output name=url::https://www.bibleserver.com/EU/${{steps.buch.outputs.name}}${{steps.kapitel.outputs.stelle}}"      
      - name: send titel
        uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ secrets.MATRIX_ROOM_ID }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          message: |
               ${{on.rss.outputs.title}}
               (${{steps.link.outputs.url}})
              
          server: "synod.im"
      - name: send psalm
        uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ secrets.MATRIX_ROOM_ID }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          message: |
               ${{on.rss.outputs.content}}
               
          server: "synod.im"
      - name: send fuss
        uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ secrets.MATRIX_ROOM_ID }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          message: |

               ----------
               ${{on.rss.outputs.url}}
          server: "synod.im"          
